### ISSUE TITLE
Find out how to aggegrate the Github project boards

### ISSUE THREAD

**Issue by Sander3003** [com-pas/contributing#14]
As a CoMPAS community member
I need to have an overview of the github issues/tickets
So I can see what other community members are working on and contact them if relevant

Acceptance criteria:
- Use Github (if possible)
- Document the proces on the wiki: https://wiki.lfenergy.org/ and the technology used
- Research and implementation (if possible)

**Comment by Sander3003** [comment]
https://docs.github.com/en/github/managing-your-work-on-github/about-project-boards

**Comment by Flurb** [comment]
Should this be documented on the LFEnergy wiki @Sander3003 ?
Because it's done, but not documented.

**Comment by Sander3003** [comment]
A note on https://github.com/com-pas/contributing/blob/master/CONTRIBUTING.md could be enough. It would be nice if new contributors know where to look for open issues.

**Comment by dlabordus** [comment]
It's described on the Architectuur site under Issue Management (https://com-pas.github.io/compas-architecture/ISSUE_MANAGEMENT.html)
