### ISSUE TITLE
Add to contributing guideline: repository description

### ISSUE THREAD

**Issue by Sander3003** [com-pas/contributing#17]
As a developer
I want to have guidelines to describe the CoMPAS repositories
So I can see the goal of this component

Background:
Unclear what the role is of a specific repository

Acceptance criteria:
Criteria for a good repo descriptions

**Comment by Flurb** [comment]
@dlabordus @Sander3003 Every repository has a README with descriptions, is this enough for now?

**Comment by Sander3003** [comment]
Good for now.
