### ISSUE TITLE
Community processes

### ISSUE THREAD

**Issue by Sander3003** [com-pas/contributing#19]
As a developer/user
I need to have a clear picture of the community processes
So I can work and collaborate efficiently

Acceptence criteria:
Describe refinements/weekly stand-up meeting

**Comment by Sander3003** [comment]
@AliouDIAITE can you check what is missing on this topic?

**Comment by Flurb** [comment]
@dlabordus @Sander3003 I think this one can be closed.

**Comment by Sander3003** [comment]
https://com-pas.github.io/contributing/
