### ISSUE TITLE
Allow slack access

### ISSUE THREAD

**Issue by danyill** [com-pas/contributing#26]
Currently Slack access appears to be tied to specific domains:

![image](https://user-images.githubusercontent.com/674783/125208528-2752e980-e2e7-11eb-9f4c-fa3a8a20cba4.png)

As CONTRIBUTING.md rightly points out:

>One of the first important things, is to meet the community. Feel free to introduce yourself on our Slack channel!

Can open access be provided to this channel or a mechanism be provided to allow users to request access?

**Comment by Sander3003** [comment]
@danyill thanks for reporting the issue, @jmertic is their a way to fix this?

**Comment by Sander3003** [comment]
https://join.slack.com/t/lfenergy/shared_invite/zt-f9z7c305-SYbhNb2ffXJ~8jGd_gpwWQ @danyill does this work?

**Comment by jmertic** [comment]
You can use https://slack.lfenergy.org/ which is a Slack invited that anyone can join.

**Comment by Sander3003** [comment]
We need to add this to CONTRIBUTING.md to me more clear! Thanks for the suggestion @jmertic.

**Comment by Sander3003** [comment]
https://github.com/com-pas/contributing/pull/27/

**Comment by danyill** [comment]
Thanks, that works great.
