### ISSUE TITLE
Change Norbert Armand to Patrick Montaner in TSC member

### ISSUE THREAD

**Issue by FredFousPro** [com-pas/contributing#4]
Wait for GitHub account information from Patrick.

**Comment by Sander3003** [comment]
@FredFousPro is this still relevant or can this issue be closed?

**Comment by FredFousPro** [comment]
Yes, but I couldn't do it because Patrick was not subscribed to GitHub.

**Comment by Sander3003** [comment]
Thanks for the update! You can close this issue once it is done or not relevant.

**Comment by Sander3003** [comment]
See https://github.com/com-pas/contributing/pull/36
