### ISSUE TITLE
OpenSSF Best Practices Badges - Vulnerability report process

### ISSUE THREAD

**Issue by FredFousPro** [com-pas/contributing#47]
In order to fully validate the silver level of OpenSSF Best Practices Badges for our project, we have to documented the process for responding to vulnerability reports.

Here is the requirement to meet:
The project MUST have a documented process for responding to vulnerability reports. (URL required) [vulnerability_response_process] 
This is strongly related to vulnerability_report_process, which requires that there be a documented way to report vulnerabilities. It also related to vulnerability_report_response, which requires response to vulnerability reports within a certain time frame.

Here is the questionnaire :
https://bestpractices.coreinfrastructure.org/en/projects/5925?criteria_level=1

**Comment by Sander3003** [comment]
Done; we enabled this: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-an-organization

**Comment by Sander3003** [comment]
@AliouDIAITE can you update it in the SSF best pratices environement? If done, we can close this one.

**Comment by AliouDIAITE** [comment]
Done

**Comment by Sander3003** [comment]
Great news @AliouDIAITE , we do have control over the best practices badge ;)
